# Numpy.array 的基本操作

In [2]:
import numpy as np

In [3]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
X =np.arange(15).reshape(3,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

### 数组的维度

In [5]:
x.ndim

1

In [6]:
X.ndim

2

In [7]:
x.shape

(10,)

In [8]:
X.shape

(3, 5)

In [9]:
# 大小
x.size

10

In [10]:
X.size

15

## 数据访问

In [11]:
x[0]

0

In [12]:
x[-1]

9

In [13]:
X[0][1]

1

In [14]:
X[(0,1)]

1

In [15]:
X[0,1]

1

In [16]:
x[0:5]

array([0, 1, 2, 3, 4])

In [17]:
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
x[::2]

array([0, 2, 4, 6, 8])

In [20]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [21]:
# 对于 numpy，可以访问每一维的切片
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [22]:
# 返回二维数组的前两行
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
# 分解成两个命令看的更直观, X[:2]:[:3] 是以 X[:2] 的结果为输入返回前三个元素，随意还是两个
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [24]:
# 前两行，间隔为2的结果，其实就是把切片放到不同的维度
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [25]:
# 行，列反转
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [26]:
# 获取第一行
X[0, :]

array([0, 1, 2, 3, 4])

In [27]:
# 可以看到维度是1
X[0, :].ndim

1

In [28]:
# 取一列, :所有的行， 0表示每一行的第一个元素
X[:, 0]

array([ 0,  5, 10])

In [29]:
## 结果的维度是 1 维的数组
X[:, 0].ndim

1

In [30]:
# 子矩阵和原矩阵是共享元素的，修改其中一个会影响另外一个
subX=X[:2,:3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
subX[0,0]=100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [32]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [33]:
# 获取独立的子矩阵
subX=X[:2,:3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

## Reshape 修改维度

In [34]:
x.shape

(10,)

In [35]:
x.ndim

1

In [36]:
# 修改为 2*5, 不会修改x本身
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [37]:
# 可以指定一个参数，另外一个维度会自动计算
x.reshape(10,-1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [38]:
x.reshape(-1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [39]:
x.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 合并操作

In [40]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [41]:
x

array([1, 2, 3])

In [43]:
y

array([3, 2, 1])

In [44]:
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [45]:
A = np.array([[1,2,3],
              [4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.concatenate([A,A], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
np.concatenate([A,A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
np.concatenate([A,y.reshape(1,-1)])

array([[1, 2, 3],
       [4, 5, 6],
       [3, 2, 1]])

In [49]:
np.vstack([A,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [51]:
B=np.full((2,2),100)
B

array([[100, 100],
       [100, 100]])

In [53]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

### 分割

In [54]:
x =np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
x1,x2,x3=np.split(x,[3,7])

In [57]:
x1

array([0, 1, 2])

In [58]:
x2

array([3, 4, 5, 6])

In [59]:
x3

array([7, 8, 9])

In [60]:
x1,x2 =np.split(x,[5])

In [61]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
# 分割多维数组，横向分割
A1,A2 =np.split(A,[2])

In [66]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [64]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
A1+A2

array([[ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [68]:
# 分割多维数组，横向分割
A1,A2 =np.split(A,[2],axis=1)

In [69]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [70]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [71]:
upper,lower = np.vsplit(A,[2])

In [72]:
left, right =np.hsplit(A, [2])

In [73]:
data= np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [74]:
X, y=np.hsplit(data, [-1])

In [75]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [76]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [77]:
y[:,0]

array([ 3,  7, 11, 15])