# 07-numpy.array中的运算

给定一个向量，让向量中每一个数乘以2
a=(0,1,2)
a'2=(0,2,4)

In [2]:
n=10
L =[i for i in range(n)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
# 和我们预期的不同， *2 的操作把数组的长度翻倍了
L * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
import numpy as np

In [5]:
n = 100000
L =np.arange(n)

In [10]:
%%time
A =np.array(2*e for e in L)

CPU times: user 19 µs, sys: 2 µs, total: 21 µs
Wall time: 24.8 µs


In [11]:
%%time
# 支持直接计算
A = 2 * L

CPU times: user 497 µs, sys: 145 µs, total: 642 µs
Wall time: 431 µs


In [12]:
A

array([     0,      2,      4, ..., 199994, 199996, 199998])

In [13]:
n=10
L=np.arange(n)
2 * L

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Universal Functions

In [14]:
X=np.arange(1, 16).reshape((3, 5))

In [15]:
X -1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
X +1

array([[ 2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16]])

In [17]:
X *2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30]])

In [20]:
# 小数除法
X / 2

array([[0.5, 1. , 1.5, 2. , 2.5],
       [3. , 3.5, 4. , 4.5, 5. ],
       [5.5, 6. , 6.5, 7. , 7.5]])

In [19]:
# 整数除法
X //2

array([[0, 1, 1, 2, 2],
       [3, 3, 4, 4, 5],
       [5, 6, 6, 7, 7]])

In [21]:
# 幂运算
X ** 2

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100],
       [121, 144, 169, 196, 225]])

In [22]:
X % 2

array([[1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]])

In [23]:
1 / X

array([[1.        , 0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [0.09090909, 0.08333333, 0.07692308, 0.07142857, 0.06666667]])

In [24]:
np.abs(X)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
np.sign(X)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [26]:
np.cos(X)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219],
       [ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153],
       [ 0.0044257 ,  0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [27]:
np.tan(X)

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00, -3.38051501e+00],
       [-2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01,  6.48360827e-01],
       [-2.25950846e+02, -6.35859929e-01,  4.63021133e-01,
         7.24460662e+00, -8.55993401e-01]])

In [28]:
np.exp(X)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
        1.48413159e+02],
       [4.03428793e+02, 1.09663316e+03, 2.98095799e+03, 8.10308393e+03,
        2.20264658e+04],
       [5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
        3.26901737e+06]])

In [29]:
np.power(3,X)

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [30]:
3 ** X

array([[       3,        9,       27,       81,      243],
       [     729,     2187,     6561,    19683,    59049],
       [  177147,   531441,  1594323,  4782969, 14348907]])

In [31]:
np.log(X)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509],
       [2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ]])

In [32]:
np.log2(X)

array([[0.        , 1.        , 1.5849625 , 2.        , 2.32192809],
       [2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809],
       [3.45943162, 3.5849625 , 3.70043972, 3.80735492, 3.9068906 ]])

In [33]:
np.log10(X)

array([[0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ],
       [0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ],
       [1.04139269, 1.07918125, 1.11394335, 1.14612804, 1.17609126]])

## 矩阵运算

In [34]:
A = np.arange(4).reshape(2, 2)
B = np.full((2,2),10)

In [35]:
# 数学运算符是矩阵相应位置的数字之间的计算
A - B

array([[-10,  -9],
       [ -8,  -7]])

In [37]:
# 矩阵乘法
A.dot(B)

array([[10, 10],
       [50, 50]])

In [38]:
# 矩阵的转置
A.T

array([[0, 2],
       [1, 3]])

## 向量和矩阵的运算

In [39]:
v = np.array([1, 21])

In [40]:
A

array([[0, 1],
       [2, 3]])

In [41]:
A + v

array([[ 1, 22],
       [ 3, 24]])

In [42]:
# 先转换成矩阵
np.vstack([v]*A.shape[0])

array([[ 1, 21],
       [ 1, 21]])

In [44]:
# 效果和 A+v 一样
np.vstack([v]*A.shape[0]) + A

array([[ 1, 22],
       [ 3, 24]])

In [46]:
np.tile(v, (2, 1)) + A

array([[ 1, 22],
       [ 3, 24]])

In [47]:
v , A

(array([ 1, 21]),
 array([[0, 1],
        [2, 3]]))

In [48]:
v.dot(A)

array([42, 64])

In [49]:
A.dot(v)

array([21, 65])

## 矩阵的逆
方阵才存在逆矩阵
非方阵可以求伪逆矩阵

In [50]:
A

array([[0, 1],
       [2, 3]])

In [51]:
invA = np.linalg.inv(A)
invA

array([[-1.5,  0.5],
       [ 1. ,  0. ]])

In [52]:
# 原矩阵 * 逆矩阵 = 单位矩阵
A.dot(invA)

array([[1., 0.],
       [0., 1.]])

In [53]:
invA.dot(A)

array([[1., 0.],
       [0., 1.]])

In [55]:
X=np.arange(16).reshape((2, 8))
# np. linalg. inv(X) 会报错
pinvX = np. linalg.pinv(X)
pinvX

array([[-1.35416667e-01,  5.20833333e-02],
       [-1.01190476e-01,  4.16666667e-02],
       [-6.69642857e-02,  3.12500000e-02],
       [-3.27380952e-02,  2.08333333e-02],
       [ 1.48809524e-03,  1.04166667e-02],
       [ 3.57142857e-02, -7.30583920e-18],
       [ 6.99404762e-02, -1.04166667e-02],
       [ 1.04166667e-01, -2.08333333e-02]])

In [57]:
# 对角线也是1
X.dot(pinvX)

array([[ 1.00000000e+00, -2.77555756e-16],
       [ 1.69309011e-15,  1.00000000e+00]])