# 聚合操作
把一组值变成一个值

In [1]:
import numpy as np
L= np.random.random(100)
L

array([0.72326419, 0.20097317, 0.25200886, 0.15532317, 0.44284488,
       0.34981929, 0.10329279, 0.54924853, 0.38526933, 0.91743401,
       0.91829964, 0.37982152, 0.7745773 , 0.95449407, 0.0024987 ,
       0.65757822, 0.58874457, 0.48368505, 0.22088482, 0.80696247,
       0.62069723, 0.64096345, 0.74001712, 0.59684299, 0.94797101,
       0.13176394, 0.45240052, 0.34784361, 0.06690425, 0.86964377,
       0.70376632, 0.31564304, 0.67230223, 0.87415401, 0.22359073,
       0.73999949, 0.68793281, 0.72120763, 0.17497419, 0.70098832,
       0.58855457, 0.28547496, 0.96161386, 0.77310071, 0.60128933,
       0.15372087, 0.22923523, 0.48724652, 0.57496173, 0.65983825,
       0.62516407, 0.37313876, 0.03139475, 0.12073242, 0.70779175,
       0.99262849, 0.09775614, 0.88414857, 0.17409265, 0.34630871,
       0.64792922, 0.77852759, 0.02787402, 0.65229745, 0.03035071,
       0.68254526, 0.58913309, 0.42651214, 0.42867041, 0.2935559 ,
       0.55583925, 0.28310907, 0.08153372, 0.25928528, 0.81128

In [2]:
sum(L)

50.48845963252683

In [4]:
# 效率更高
np.sum(L)

50.48845963252686

In [7]:
big_array=np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

70.4 ms ± 1.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
332 µs ± 16 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [8]:
np.min(big_array)

2.3641815456443283e-06

In [9]:
np.max(big_array)

0.9999990543007586

In [12]:
big_array.min()

0.9999990543007586

In [13]:
big_array.max()

0.9999990543007586

In [16]:
X = np.arange(16).reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
# 所有元素求和
np.sum(X)

120

In [19]:
# 列求和
np.sum(X, axis=0)

array([24, 28, 32, 36])

In [20]:
# 行求和
np.sum(X, axis=1)

array([ 6, 22, 38, 54])

In [22]:
np.prod(X)

0

In [37]:
np.prod(X+1)*np.prod(X+1)

/var/folders/f1/g3609vj57txbrf85ndk_ml1r0000gp/T/ipykernel_77458/1722935144.py:1: RuntimeWarning: overflow encountered in long_scalars
  np.prod(X+1)*np.prod(X+1)


3543051899458551808

In [23]:
# 平均值
np.mean(X)

7.5

In [24]:
# 中位数
np.median(X)

7.5

In [29]:
v=np.array([1,1,2,2,10])
np.mean(v)

3.2

In [30]:
np.median(v)

2.0

In [33]:
np.percentile(big_array,99.99)

0.9999055156894061

In [35]:
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(big_array,percent))

2.3641815456443283e-06
0.2499233801773716
0.4996968148382796
0.7496748711646809
0.9999990543007586


In [38]:
# 方差
np.var(big_array)

0.08325372462005069

In [39]:
# 标准差
np.std(big_array)

0.2885372153120819

## 索引
np.arg 返回索引位置

In [42]:
X= np.random.normal(0, 1, size=1000000)

In [47]:
# 最小值的索引位置
np.argmin(X)

27948

In [46]:
np.min(X) == X[np.argmin(X)]

True

## 排序和使用索引

In [48]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [50]:
np.random.shuffle(x)
x

array([10,  1, 14,  2,  6,  7, 12, 15,  8,  5,  0,  3,  4,  9, 13, 11])

In [54]:
# 返回新的排序向量
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [53]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [56]:
# 生成随机矩阵
X = np.random.randint(10,size=(4,4))
X

array([[7, 9, 3, 8],
       [0, 9, 9, 8],
       [0, 3, 5, 3],
       [7, 9, 8, 9]])

In [58]:
# 每一行排序
np.sort(X,axis=1)

array([[3, 7, 8, 9],
       [0, 8, 9, 9],
       [0, 3, 3, 5],
       [7, 8, 9, 9]])

In [59]:
np.sort(X,axis=0)

array([[0, 3, 3, 3],
       [0, 9, 5, 8],
       [7, 9, 8, 8],
       [7, 9, 9, 9]])

In [60]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
np.random.shuffle(x)
x

array([10,  1,  2,  3, 13,  5, 11,  9,  4,  7, 15, 12,  8, 14,  0,  6])

In [62]:
# 返回排序的索引
np.argsort(x)

array([14,  1,  2,  3,  8,  5, 15,  9, 12,  7,  0,  6, 11,  4, 13, 10])

In [65]:
np.random.shuffle(x)
np.partition(x, 3)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 10, 12, 13, 14, 15])

In [66]:
np.argpartition(x, 3)

array([12,  9,  8, 15,  2,  4,  5, 10,  3, 13,  1, 11,  6,  0, 14,  7])

In [67]:
X

array([[7, 9, 3, 8],
       [0, 9, 9, 8],
       [0, 3, 5, 3],
       [7, 9, 8, 9]])

In [71]:
# arg 同样可以用在矩阵，其他 arg 方法也是一样的
np.argsort(X,axis=1)

array([[2, 0, 3, 1],
       [0, 3, 1, 2],
       [0, 1, 3, 2],
       [0, 2, 1, 3]])