# 03.numpy.array基础

In [1]:
import numpy

In [2]:
numpy.__version__

'1.22.1'

In [3]:
numpy.__git_version__

'7ce4118531b585b5d8f0380c6b896ae22d93bd96'

In [4]:
import numpy as np

In [5]:
np.__version__

'1.22.1'

# 默认数组是弱类型的，一个数组可以保存不同的数据类型

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L[1] = "why"
L

[0, 'why', 2, 3, 4, 5, 6, 7, 8, 9]

# python array 的缺点

In [10]:
import array

In [12]:
arr = array.array('i',[i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[1] = ''

TypeError: an integer is required (got type str)

# numpy.array

In [15]:
npArr = np.array([i for i in range(10)])
npArr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
npArr.dtype

dtype('int64')

### int 类型的数组只能保存 int 类型

In [18]:
npArr[1]=3.2
npArr

array([0, 3, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
npArr = np.array([1,2,3.0])
npArr

array([1., 2., 3.])

In [20]:
npArr.dtype

dtype('float64')

## 其他创建 numpy.array 数组的方法

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.zeros(10).dtype

dtype('float64')

In [23]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [30]:
np.full(shape=(3,5),fill_value=66)

array([[66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66],
       [66, 66, 66, 66, 66]])

## arrange

In [31]:
[i for i in range(0,20,2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [32]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

步长可以是 浮点数

In [33]:
np.arange(0,1,0.2)

array([0. , 0.2, 0.4, 0.6, 0.8])

默认步长 1

In [34]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### linspace

在0-20 分成10个元素，包括0和20，生成的是等差数列

In [36]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [37]:
np.linspace(0,20,11)

array([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

### random

In [38]:
np.random.randint(0,10)

3

In [39]:
np.random.randint(0,10,10)

array([8, 9, 8, 3, 8, 5, 1, 6, 1, 6])

In [40]:
np.random.randint(4,8,size=10)

array([7, 5, 7, 7, 4, 4, 5, 6, 5, 6])

In [41]:
np.random.randint(4,8,size=(3,5))

array([[5, 4, 6, 5, 4],
       [6, 5, 4, 4, 7],
       [4, 5, 7, 5, 5]])

In [42]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [43]:
np.random.seed(666)
np.random.randint(4,8,size=(3,5))

array([[4, 6, 5, 6, 6],
       [6, 5, 6, 4, 5],
       [7, 6, 7, 4, 7]])

In [44]:
np.random.random()

0.2811684913927954

In [46]:
np.random.random(12)

array([0.29097383, 0.84778197, 0.3497619 , 0.92389692, 0.29489453,
       0.52438061, 0.94253896, 0.07473949, 0.27646251, 0.4675855 ,
       0.31581532, 0.39016259])

In [45]:
np.random.random((3,4))

array([[0.46284169, 0.23340091, 0.76706421, 0.81995656],
       [0.39747625, 0.31644109, 0.15551206, 0.73460987],
       [0.73159555, 0.8578588 , 0.76741234, 0.95323137]])

In [47]:
np.random.normal()

0.9047266176428719

In [48]:
np.random.normal(0,1,(3,5))

array([[-0.82628327,  0.82101369,  0.36712592,  1.65399586,  0.13946473],
       [-1.21715355, -0.99494737, -1.56448586, -1.62879004,  1.23174866],
       [-0.91360034, -0.27084407,  1.42024914, -0.98226439,  0.80976498]])

In [52]:
np.random.normal?

In [51]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the ``normal`` method of a ``default_rng()``
        instance instead; please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution