# Fancy-indexing

In [1]:
import numpy as np
x= np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [2]:
# 切片方式
x[3:9:2]

array([3, 5, 7])

In [3]:
# 下标方式
x[3]

3

In [4]:
# 定义索引数据，当作下标传入，可以返回下标的值，这就是fancy indexing
ind = [3,5,8]
x[ind]

array([3, 5, 8])

In [9]:
# 也可以定义一个二维矩阵，这时 fancy indexing 生成的是二维矩阵对应索引值的二维矩阵
ind = np.array([[0,2],
                 [1,3]])
x[ind]

array([[0, 2],
       [1, 3]])

In [10]:
X = x.reshape(4,-1)
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
# 可以定义 row/col，传入到 X，返回对应 行列的索引值
row=np.array([0, 1, 2])
col=np.array([1, 2, 3])
X[row,col]

array([ 1,  6, 11])

In [14]:
X[0,col]

array([1, 2, 3])

In [15]:
X[:2,col]

array([[1, 2, 3],
       [5, 6, 7]])

In [16]:
# 也可以使用 boolean 数组
col = [True, False, True, True]
X[1:3, col]

array([[ 4,  6,  7],
       [ 8, 10, 11]])

## numpy.array 的比较

In [17]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
x < 3

array([ True,  True,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [19]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [20]:
x == 3

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False])

In [21]:
2 * x == 24 - 4 * x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False])

In [22]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [24]:
# 也可以得到 boolean 矩阵
X < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [25]:
np.sum(x <=3)

4

In [26]:
np.count_nonzero(x <=3)

4

In [27]:
# 是否有0的元素
np.any(x==0)

True

In [29]:
# 是否所有元素都大于 0
np.all(x >= 0)

True

In [37]:
# 条件也可以组合使用， & 按照索引位置分别与运算
np.sum((x>3)&(x<10))

6

In [40]:
# 年龄不等于0
np.sum(~(x==0))

15

In [31]:
np.sum(X %2 == 0)

8

In [33]:
# 每一行有多少偶数
np.sum(X %2 == 0,axis=1)

array([2, 2, 2, 2])

In [41]:
# 最后一列被3整除的行数据
X[X[:,3]%3==0,:]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])